version: "3.4"
services:
  postgres:
    container_name: postgres-db
    network_mode: bridge
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: threads
    ports:
      - 5542:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
